DB3/DB3/Controllers/CompanyController.cs
using DB3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DB3.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult CompanyList()
        {
            DB3Entities3 e = new DB3Entities3();
            List<CompanyModel> cml = new List<CompanyModel>();
            List<Company> cl = e.Companies.ToList();
            foreach(Company c in cl)
            {
                CompanyModel cm = new CompanyModel();
                cm.id = c.Company_id;
                cm.Name = c.C_Name;
                cm.Address = c.Address;
                cm.Contact = c.Mobile_Number;
                cml.Add(cm);
            }

            return View(cml);
        }

        // GET: Company/Details/5
        public ActionResult CompanyDetails(int id)
        {
            DB3Entities3 e = new DB3Entities3();
            var company = e.Companies.Where(x => x.Company_id == id).First();
            CompanyModel cm = new CompanyModel();
            cm.Name = company.C_Name;
            cm.Address = company.Address;
            cm.Contact = company.Mobile_Number;

            return View(cm);
        }

        // GET: Company/Create
        public ActionResult CompanyAdd()
        {

            return View();
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult CompanyAdd(CompanyModel obj)
        {
            try
            {
                // TODO: Add insert logic here
                Company company = new Company();
                company.C_Name = obj.Name;
                company.Address = obj.Address;
                company.Mobile_Number = obj.Contact;

                DB3Entities3 e = new DB3Entities3();
                e.Companies.Add(company);
                e.SaveChanges();

                ViewBag.message = "Data is Successfully added";
                //Session["CompanyId"] = company.Company_id;
                return RedirectToAction("CompanyDetails", new { id = company.Company_id });
            }
            catch(Exception ex)
            {
                //ViewBag.message = "Data is not added ";
                throw ex;
            }
        }

        // GET: Company/Edit/5
        public ActionResult CompanyEdit(int id)
        {
            DB3Entities3 entity = new DB3Entities3();
            var company = entity.Companies.Where(x => x.Company_id == id).First();
            CompanyModel cm = new CompanyModel();
            cm.Name = company.C_Name;
            cm.Address = company.Address;
            cm.Contact = company.Mobile_Number;

            return View(cm);
          
        }

        // POST: Company/Edit/5
        [HttpPost]
        public ActionResult CompanyEdit(int id, CompanyModel obj)
        {
            try
            {
                // TODO: Add update logic here
                DB3Entities3 entity = new DB3Entities3();
                var company = entity.Companies.Where(x => x.Company_id == id).First();
               // Company c = new Company();
                company.C_Name = obj.Name;
                company.Address = obj.Address;
                company.Mobile_Number = obj.Contact;
                //e.Companies.Add(c);
                entity.SaveChanges();

                ViewBag.message = "Data is Successfully edited";
                return RedirectToAction("CompanyDetails", new { id = company.Company_id });
            }
            catch(Exception ex)
            {
               throw ex;
            }
        }

        // GET: Company/Delete/5
        public ActionResult CompanyDelete(int id)
        {
            DB3Entities3 entity = new DB3Entities3();
            var c = entity.Companies.Where(x => x.Company_id == id).First();
            CompanyModel cm = new CompanyModel();
            cm.Name = c.C_Name;
            cm.Address = c.Address;
            cm.Contact = c.Mobile_Number;
            return View(cm);
        }

        // POST: Company/Delete/5
        [HttpPost]
        public ActionResult CompanyDelete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DB3Entities3 entity = new DB3Entities3();
                //var c = entity.Companies.Where(x => x.Company_id == id).First();
                //c.Company_id = 0;
                int r = entity.prDelCompany(id);
                entity.SaveChanges();
                return RedirectToAction("CompanyList");
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
    }
}

DB3/DB3/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB3.Models;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace DB3.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            //
            DB3Entities2 db = new DB3Entities2();
            List<Order> o = db.Orders.ToList();
            List<OrderViewModel> ol = new List<OrderViewModel>();
            //OrderViewModel oi = new OrderViewModel();
            foreach(Order s in o)
            {
                OrderViewModel oi = new OrderViewModel();
                oi.order_id = s.order_id;
               // oi.Medicine_Name = s.Medicine_Name;
               // oi.Quantity = s.Quantity;
               // oi.Price = s.Price;
                Medicine c = db.Medicines.Where(x => x.Medicine_id == s.medicine_id).First();
                oi.Medicine_Name = c.Medicine_Name;
                oi.type = c.Type;
                //oi.medicine_id = s.medicine_id;
                ol.Add(oi);
            }
            return View(ol);
        }
        public ActionResult OrderReport()
        {
            DB3Entities2 db = new DB3Entities2();
            List<Order> exam = new List<Order>();
            exam = db.Orders.ToList();


            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Report"), "CrystalReport2.rpt"));

            rd.SetDataSource(exam);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "OrderList.pdf");
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(OrderViewModel s)
        {
            try
            {
                DB3Entities2 db = new DB3Entities2();
               // Order o = new Order();
                var order = new Order();
                order.Medicine_Name = s.Medicine_Name;
                order.Quantity = s.Quantity;
                order.Price = s.Price;
                var c = db.Medicines.Where(x => x.Medicine_Name == s.Medicine_Name).First();
                order.medicine_id = c.Medicine_id;
                //var d = db.Medicines.Where(x => x.Medicine_id == s.medicine_id).First();
               
                db.Orders.Add(order);
                db.SaveChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            DB3Entities2 db = new DB3Entities2();
            
            var s = db.Orders.Where(x => x.order_id == id).First();
            //List<Order> c = db.Orders.ToList();
           OrderViewModel cs = new OrderViewModel();
           
                    cs.Medicine_Name = s.Medicine_Name;
                   // cs.Quantity = s.Quantity;
                   // cs.Price = s.Price;
            var g = db.Medicines.Where(x => x.Medicine_id == s.medicine_id).First();
            cs.type = g.Type;    
                    //cs.medicine_id = s.medicine_id;
                
            return View(cs);
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(OrderViewModel s,int id)
        {
            try
            {
                DB3Entities2 db = new DB3Entities2();
                
                var cs = db.Orders.Where(x => x.order_id == id).First();
                List<Order> c = db.Orders.ToList();
                
                        s.Medicine_Name = cs.Medicine_Name;
                       // s.Quantity = cs.Quantity;
                       // s.Price = cs.Price;
                // var g = db.Medicines.Where()
                       // s.medicine_id = cs.medicine_id;
                        db.SaveChanges();
                    
                // TODO: Add update logic here

                return RedirectToAction("Index", new { id =cs.medicine_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Order/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DB3/DB3/Controllers/SellsController.cs
using DB3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DB3.Controllers
{
    public class SellsController : Controller
    {
        // GET: Sells
        public ActionResult SellList()
        {
           /* DB3Entities2 entity = new DB3Entities2();
            List<Sell> l = entity.Sells.ToList();
            List<SellsModel> sl = new List<SellsModel>();
            foreach(Sell s in l)
            {
                SellsModel sm = new SellsModel();
                sm.date = Convert.ToDateTime(s.Date);
                sm.quantity = Convert.ToInt32( s.Quantity);
                sm.total = Convert.ToInt32(s.Total);
                sm.id = s.Sell_Id;
                sl.Add(sm);
            }*/
            SellsModel m = new SellsModel();

            return View(m.getlist());
        }

        // GET: Sells/Details/5
        public ActionResult SellDetails(int id)
        {
            SellsModel sm = new SellsModel();
            return View(sm.getdetail(id));
        }

        // GET: Sells/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sells/Create
        [HttpPost]
        public ActionResult SellAdd(SellsModel obj)
        {
            try
            {
                // TODO: Add insert logic here
              
                return RedirectToAction("SellList");
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        // GET: Sells/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sells/Edit/5
        [HttpPost]
        public ActionResult SellEdit(int ID, SellsModel obj)
        {
           
                // TODO: Add update logic here
                SellsModel sm = new SellsModel();
            if (sm.edited(ID, obj) == true)
                return RedirectToAction("SellDetails", new { id = ID} );
            else
                ViewBag.Message = " Data connot be Updated";
                return RedirectToAction("SellList");

        }

        // GET: Sells/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sells/Delete/5
        [HttpPost]
        public ActionResult SellDelete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DB3Entities3 entity = new DB3Entities3();
                var s = entity.Sells.Where(x => x.Sell_Id == id).First();
                entity.Sells.Remove(s);
                entity.SaveChanges();
                return RedirectToAction("SellList");
            }
            catch
            {
                return View();
            }
        }
    }
}

DB3/DB3/Views/Shared/_Layoutadmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Medico Club a Medical Category Bootstrap responsive Website Template | Home :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Medico Club Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- bootstrap-css -->
    <link href="~/Content/template/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <!--// bootstrap-css -->
    <!-- css -->
    <link rel="stylesheet" href="~/Content/template/css/style.css" type="text/css" media="all" />
    <!--// css -->
    <!-- font-awesome icons -->
    <link href="~/Content/template/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome icons -->
    <!-- portfolio -->
    <link rel="stylesheet" href="~/Content/template/css/chocolat.css" type="text/css" media="all">
    <!-- //portfolio -->
    <!-- font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
    <!-- //font -->
    <script src="~/Content/template/js/jquery-1.11.1.min.js"></script>
    <script src="~/Content/template/js/bootstrap.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <!-- banner -->
    <div class="banner jarallax">
        <div class="agileinfo-dot">
            <div class="header-top">
                <div class="header">
                    <div class="header-top-info">
                        <nav class="navbar navbar-default">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <div class="agileits-logo">
                                    <h1><a href="#">Medico <span>Club</span></a></h1>
                                </div>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                                <nav>
                                    <ul class="nav navbar-nav">
                                        <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                                        <li><a href="@Url.Action("MedicineList", "Medicine")">Medicine Stock</a></li>
                                        <li><a href="@Url.Action("SellList", "Sells")">Sell</a></li>
                                        <li><a href="@Url.Action("CompanyList", "Company")">Companies</a></li>
                                        <li><a href="@Url.Action("Index", "Order")">Order</a></li>
                                        <li><a href="@Url.Action("StaffIndex", "Staff")">Staff</a></li>
                                        <li><a href="@Url.Action("Index", "Home")">Logout</a></li>

                                    </ul>
                                </nav>
                            </div>
                            <!-- /.navbar-collapse -->
                        </nav>
                    </div>
                </div>
            </div>
            <div class="w3layouts-banner-info">
                <div class="container">
                    <div class="w3layouts-banner-slider">
                        <div class="w3layouts-banner-top-slider">
                            <div class="slider">
                                <div class="callbacks_container">
                                    <ul class="rslides callbacks callbacks1" id="slider4">
                                        <li>
                                            <div class="w3ls-text">
                                                <div class="w3ls-text-info">
                                                    <h2>Health<span>is better</span><span> than </span><span> Wealth...</span></h2>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="w3ls-text">
                                                <div class="w3ls-text-info">
                                                    <h2><span>be healthy</span><span>and</span>positive</h2>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="clearfix"> </div>
                                <script src="~/Content/template/js/responsiveslides.min.js"></script>
                                <script>
                                    // You can also use "$(window).load(function() {"
                                    $(function () {
                                        // Slideshow 4
                                        $("#slider4").responsiveSlides({
                                            auto:  true,
                                            pager: true,
                                            nav: true,
                                            speed: 500,
                                            namespace: "callbacks",
                                            before: function () {
                                                $('.events').append("<li>before event fired.</li>");
                                            },
                                            after: function () {
                                                $('.events').append("<li>after event fired.</li>");
                                            }
                                        });

                                    });
                                </script>
                                <!--banner Slider starts Here-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- //banner -->
    <div>
        @RenderBody()
    </div>
    <div class="contact" id="mail">
        <div class="container">
            <div class="agileits-heading">
                <h3>Contact</h3>
            </div>
            <div class="w3layouts-contact-grids">
                <div class="col-sm-3 w3layouts-contact-grid">
                    <i class="fa fa-map" aria-hidden="true"></i>
                    <h5>Address</h5>
                    <p>UET CSE Department Lahore</p>
                </div>
                <div class="col-sm-3 w3layouts-contact-grid">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <h5>Phone/Fax</h5>
                    <p>+92 42 99029216</p>
                    <p>+92 42 99029227</p>
                </div>
                <div class="col-sm-3 w3layouts-contact-grid">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    <h5>Email</h5>
                    <p><a href="www.uet.edu.pk"> registrar@uet.edu.pk</a></p>
                    <p><a href="www.uet.edu.pk"> abidumer@uet.edu.pk</a></p>
                </div>
                <div class="col-sm-3 w3layouts-contact-grid">
                    <i class="fa fa-share-alt" aria-hidden="true"></i>
                    <h5>Social</h5>
                    <p>Touch With Us</p>
                    <div class="agileinfo-social-grids">
                        <ul>
                            =
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-rss"></i></a></li>
                            <li><a href="#"><i class="fa fa-vk"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="copyright">
                <p>© 2019 Medico Club. All rights reserved.</p>
            </div>
        </div>
    </footer>
    <!-- //footer -->
    <script src="~/Content/template/js/jarallax.js"></script>
    <script src="~/Content/template/js/SmoothScroll.min.js"></script>
    <script type="text/javascript">
        /* init Jarallax */
        $('.jarallax').jarallax({
            speed: 0.5,
            imgWidth: 1366,
            imgHeight: 768
        })
    </script>
    <script src="~/Content/template/js/responsiveslides.min.js"></script>
    <script type="text/javascript" src="~/Content/template/js/move-top.js"></script>
    <script type="text/javascript" src="~/Content/template/js/easing.js"></script>
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
    <!-- Tabs-JavaScript -->
    <script src="~/Content/template/js/jquery.filterizr.js"></script>
    <script src="~/Content/template/js/controls.js"></script>
    <script type="text/javascript">
        $(function () {
            $('.filtr-container').filterizr();
        });
    </script>
    <!-- //Tabs-JavaScript -->
    <!-- PopUp-Box-JavaScript -->
    <script src="~/Content/template/js/jquery.chocolat.js"></script>
    <script type="text/javascript">
        $(function () {
            $('.filtr-item a').Chocolat();
        });
    </script>
    <!-- //PopUp-Box-JavaScript -->
</body>
</html>